### ISSUE TITLE
App seems to be down?

### ISSUE THREAD

**Issue by MatteoFaelli** [fawazsullia/password-generator#4]
https://passwordinator.herokuapp.com/

<img width="519" alt="Screenshot 2022-12-08 at 12 41 40" src="https://user-images.githubusercontent.com/86773788/206437950-9b8f1678-ecd8-4055-868a-12a5e8e6a07d.png">

**Comment by fawazsullia** [comment]
The app was running on heroku free version and they ended it. I'm in the process of moving it to a new host
